{"errorType":"Error","errorMessage":"{\"success\":false,\"timestamp\":\"2025-08-08T15:25:34.863Z\",\"error\":\"spawn pg_dump ENOENT\",\"executionTimeMs\":180,\"message\":\"Database backup failed\"}","trace":["Error: {\"success\":false,\"timestamp\":\"2025-08-08T15:25:34.863Z\",\"error\":\"spawn pg_dump ENOENT\",\"executionTimeMs\":180,\"message\":\"Database backup failed\"}","    at exports.handler (/var/task/backup.js:278:11)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]}